import {createRequire} from 'node:module';
import {mkdir,writeFile,mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from '../server/local.mjs';
import assert from 'node:assert/strict';
const require=createRequire(process.env.STUDIO_NODE_PACKAGES+'/package.json');
const {chromium}=require('playwright');
const browser=await chromium.launch({headless:true,channel:'msedge'});
const errors=[];
const server=createServer({directory:await mkdtemp(join(tmpdir(),'story-studio-ui-'))});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const origin=`http://127.0.0.1:${server.address().port}`;
await mkdir('.local/checks',{recursive:true});
try {
  const owner=await browser.newContext({viewport:{width:1400,height:1000}});
  await owner.addInitScript(()=>{window.print=()=>{window.__printed=true;};});
  const page=await owner.newPage();page.on('pageerror',e=>errors.push(e.message));
  await page.goto(origin);
  const sample={id:'ui-sample',title:'共享与导出测试',description:'测试简介',updatedAt:1,characters:[{id:'c',name:'旅人'}],blocks:[{id:'b',type:'narration',text:'清晨，旅人走进森林。\n第二行保留换行。'},{id:'d',type:'dialogue',characterId:'c',text:'你好！这是一段对白。'},{id:'i',type:'image',caption:'插图示例',image:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII='}]};
  await page.locator('input[type=file]').first().setInputFiles({name:'test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(sample))});
  await page.getByRole('button',{name:'导出图片',exact:true}).click();
  const image=page.getByRole('link',{name:/下载.*png/});await image.waitFor({timeout:60000});
  const [download]=await Promise.all([page.waitForEvent('download'),image.click()]);await download.saveAs('.local/checks/story.png');
  const [popup]=await Promise.all([page.waitForEvent('popup'),page.getByRole('button',{name:'导出 PDF',exact:true}).click()]);
  await popup.waitForSelector('.story-document');await popup.emulateMedia({media:'print'});await popup.pdf({path:'.local/checks/story.pdf',format:'A4',printBackground:true});
  assert.equal(await popup.locator('.story-piece').count(),3);await popup.close();
  await page.getByRole('button',{name:'邀请共享',exact:true}).click();
  const links=page.locator('.studio-share input');await links.first().waitFor();
  const editorLink=await links.nth(0).inputValue(),readerLink=await links.nth(1).inputValue();
  const friend=await browser.newContext();const edit=await friend.newPage();edit.on('pageerror',e=>errors.push(e.message));await edit.goto(editorLink);
  await edit.getByRole('button',{name:'共享设置',exact:true}).waitFor();
  const title=edit.locator('input:not([readonly])').filter({visible:true}).first();await title.fill('朋友修改后的标题');
  await edit.getByRole('button',{name:'立即同步',exact:true}).click();
  await page.waitForFunction(()=>[...document.querySelectorAll('input')].some(e=>e.value==='朋友修改后的标题'),{},{timeout:15000});
  const reader=await browser.newContext();const read=await reader.newPage();await read.goto(readerLink);await read.getByRole('heading',{name:'朋友修改后的标题'}).waitFor();
  assert.equal(await read.getByRole('button',{name:'返回编辑',exact:true}).isDisabled(),true);
  // Pause polling in the friend context, then verify the conflict recovery UI.
  await edit.route('**/api/rooms/*',route=>route.abort());
  await page.locator('input:not([readonly])').filter({visible:true}).first().fill('作者的新版本');
  await page.getByRole('button',{name:'立即同步',exact:true}).click();
  await page.getByRole('status').filter({hasText:'已同步'}).waitFor();
  await title.fill('朋友离线写下的内容');
  await edit.unroute('**/api/rooms/*');
  await edit.getByRole('button',{name:'立即同步',exact:true}).click();
  await edit.getByRole('button',{name:'保留本地副本并载入共享版本',exact:true}).waitFor();
  await edit.getByRole('button',{name:'保留本地副本并载入共享版本',exact:true}).click();
  await edit.waitForFunction(()=>[...document.querySelectorAll('input')].some(e=>e.value==='作者的新版本'));
  await edit.getByRole('button',{name:'返回故事列表',exact:true}).click();
  await edit.getByRole('heading',{name:'朋友离线写下的内容（冲突前本地副本）',exact:true}).waitFor();
  await page.screenshot({path:'.local/checks/editor.png',fullPage:true});
  const long={...sample,title:'长篇分页测试',blocks:Array.from({length:90},(_,i)=>({id:'long-'+i,type:'narration',text:`第 ${i+1} 段：旅人继续前行。\n每一段都应该保留。\n这是第三行。`}))};
  await page.locator('input[type=file]').first().setInputFiles({name:'long.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(long))});
  await page.getByRole('button',{name:'导出图片',exact:true}).click();
  await page.getByRole('status').filter({hasText:'图片已生成'}).waitFor({timeout:60000});
  const longImages=page.getByRole('link',{name:/下载.*png/});assert.ok(await longImages.count()>1);
  for(let i=0;i<await longImages.count();i++){const [d]=await Promise.all([page.waitForEvent('download'),longImages.nth(i).click()]);await d.saveAs(`.local/checks/long-${i}.png`);}
  const [longPDF]=await Promise.all([page.waitForEvent('popup'),page.getByRole('button',{name:'导出 PDF',exact:true}).click()]);
  await longPDF.waitForSelector('.story-document');assert.equal(await longPDF.locator('.story-piece').count(),90);
  await longPDF.pdf({path:'.local/checks/long.pdf',format:'A4',printBackground:true});await longPDF.close();
  await writeFile('.local/checks/result.json',JSON.stringify({errors,image:true,pdf:true,sharedEdit:true,reader:true},null,2));
  assert.deepEqual(errors,[]);console.log('Browser checks passed: PNG, PDF, invitation, cross-context editing, reader.');
} finally { await browser.close(); await new Promise(resolve=>server.close(resolve)); }
